### ISSUE TITLE
Is the value discarded when RowKey is nil?

### ISSUE THREAD

**Issue by c000** [kamichidu/goen#5]
https://github.com/kamichidu/goen/blob/8fe7ba970e1e3a55725af185fe45555ae2962ec7/compiler.go#L169-L174

If `RowKey` is nil, it seems that the value of `curr` is discarded.
Is this expected?

**Comment by kamichidu** [comment]
i'll check it later.

**Comment by kamichidu** [comment]
it's unexpected.
fixed by 7b0161e86d671529fe32281824da5c706ce7e6bb
